### ISSUE TITLE
getting a lot of warnings about the new references

### ISSUE THREAD

**Issue by bnicenboim** [bnicenboim/bcogsci#1]
```
Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
  possibly non-existing or duplicated key(s) in bib file from package 'bcogsci':
    DillonEtAl2013

Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
  possibly non-existing or duplicated key(s) in bib file from package 'bcogsci':
    DillonEtAl2013

Warning in `[.bibentry`(be, cur) :
  subscript out of bounds (DillonEtAl2013' from package 'bcogsci')
Warning in `[.bibentry`(be, cur) : subscript out of bounds
Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
  possibly non-existing or duplicated key(s) in bib file from package 'bcogsci':
    FrankEtAl2015

Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
  possibly non-existing or duplicated key(s) in bib file from package 'bcogsci':
    FrankEtAl2015

Warning in `[.bibentry`(be, cur) :
  subscript out of bounds (FrankEtAl2015' from package 'bcogsci')
Warning in `[.bibentry`(be, cur) : subscript out of bounds
Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
  possibly non-existing or duplicated key(s) in bib file from package 'bcogsci':
    VSLK08

Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
  possibly non-existing or duplicated key(s) in bib file from package 'bcogsci':
    VSLK08

Warning in `[.bibentry`(be, cur) :
  subscript out of bounds (VSLK08' from package 'bcogsci')
Warning in `[.bibentry`(be, cur) : subscript out of bounds
Warning in get_bibentries(package = package, ..., stop_on_error = FALSE) :
  Couldn't find file REFERENCES.bib in package `lingpsych'
Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
  possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
    VasishthetalPLoSOne2013
```

One of the problems here is that you're using the bib file of another package, which is not a dependency, so, it's not installed by default. Can you copy the relevant references from lingpsych into this package?
Then there seem to be some duplicates, and not sure what else...

**Comment by vasishth** [comment]
I will just fix it, give me a minute

**Comment by vasishth** [comment]
Seems to be installing fine now:

> devtools::install_github("bnicenboim/bcogsci")
Downloading GitHub repo bnicenboim/bcogsci@HEAD
✓  checking for file ‘/private/var/folders/ds/fsl1v_v934v4j58c8b9m26jm0000gn/T/Rtmps0PAHa/remotes284e6e637e23/bnicenboim-bcogsci-a3aef87/DESCRIPTION’ ...
─  preparing ‘bcogsci’:
✓  checking DESCRIPTION meta-information ...
─  installing the package to process help pages
   Loading required namespace: bcogsci
─  saving partial Rd database (707ms)
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: ‘bcogsci/data/df_VOTenglish.rda’  ‘bcogsci/data/df_VOTmandarin.rda’  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: ‘bcogsci/data/df_buerki.rda’  ‘bcogsci/data/df_dillonE1.rda’  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: ‘bcogsci/data/df_dillonrep.rda’  ‘bcogsci/data/df_discreteagrmt.rda’  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: ‘bcogsci/data/df_dutch.rda’  ‘bcogsci/data/df_english.rda’  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: ‘bcogsci/data/df_gibsonwu.rda’  ‘bcogsci/data/df_gibsonwu2.rda’  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: ‘bcogsci/data/df_persianE1.rda’  ‘bcogsci/data/df_polarity.rda’  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: ‘bcogsci/data/df_powerpose.rda’  ‘bcogsci/data/df_red.rda’
─  building ‘bcogsci_0.0.0.9000.tar.gz’
   

   Welcome to R!

* installing *source* package ‘bcogsci’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading

   Welcome to R!


   Goodbye!

** help
*** installing help indices
** building package indices

   Welcome to R!


   Goodbye!

** testing if installed package can be loaded from temporary location

   Welcome to R!


   Goodbye!

** testing if installed package can be loaded from final location

   Welcome to R!


   Goodbye!

** testing if installed package keeps a record of temporary installation path
* DONE (bcogsci)

   Goodbye!

**Comment by bnicenboim** [comment]
yes, it works fine now
