### ISSUE TITLE
avoid lingpsych dependencies

### ISSUE THREAD

**Issue by bnicenboim** [bnicenboim/bcogsci#2]
Can we avoid the dependency with lingpsych? It installs all sort of C++ stuff that we don't need. And it was giving problems to a student with R using Chinese (I think) as the locale.

**Comment by vasishth** [comment]
lingpsych is never loaded in the book. I see it in packages.bib. Do you just want me to remove the reference, or can you do it?

**Comment by bnicenboim** [comment]
it's somehow required for bcogsci

**Comment by bnicenboim** [comment]
ah, it's because of this!!
\insertCite{smith2021encoding;textual}{lingpsych}

so it's a matter of copying the references from lingpsych to this package and replace those lines by:
\insertCite{smith2021encoding;textual}{bcogsci}

**Comment by vasishth** [comment]
Yes, I just pushed my changes. I removed this cut and paste error now. Can you check that it all works?

**Comment by vasishth** [comment]
I just fixed it, but I still get this warning many times when I reinstall the package. What am I doing wrong?

Warning in `[.bibentry`(be, cur) :
     subscript out of bounds (VasishthMertzenJaegerGelman2019' from package 'bcogsci')

Can you check that the package installs now?

**Comment by bnicenboim** [comment]
I think it's complaining that VasishthMertzenJaegerGelman2019 ref is not in the bib file

**Comment by vasishth** [comment]
I'm able to install it now without problems:


> devtools::install_github("bnicenboim/bcogsci",force=TRUE)
Downloading GitHub repo bnicenboim/bcogsci@HEAD
✓  checking for file ‘/private/var/folders/1f/k1sq7jzx7hxcbs02r6l712mh0000gn/T/RtmpVO86rp/remotes6db361ad3004/bnicenboim-bcogsci-c2bf813/DESCRIPTION’ ...
─  preparing ‘bcogsci’:
✓  checking DESCRIPTION meta-information ...
─  installing the package to process help pages
   Loading required namespace: bcogsci
─  saving partial Rd database (609ms)
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
       ‘bcogsci/data/df_VMJG18E1.rda’ ‘bcogsci/data/df_VMJG18E2.rda’
       ‘bcogsci/data/df_VMJG18E3.rda’ ‘bcogsci/data/df_VMJG18E4.rda’
       ‘bcogsci/data/df_VMJG18E5.rda’ ‘bcogsci/data/df_VMJG18E6.rda’
       ‘bcogsci/data/df_VMJG18E7.rda’ ‘bcogsci/data/df_VOTenglish.rda’
       ‘bcogsci/data/df_VOTmandarin.rda’ ‘bcogsci/data/df_buerki.rda’
       ‘bcogsci/data/df_chineseRCs.rda’ ‘bcogsci/data/df_dillonE1.rda’
       ‘bcogsci/data/df_dillonrep.rda’ ‘bcogsci/data/df_discreteagrmt.rda’
       ‘bcogsci/data/df_dutch.rda’ ‘bcogsci/data/df_english.rda’
       ‘bcogsci/data/df_gibsonwu.rda’ ‘bcogsci/data/df_gibsonwu2.rda’
       ‘bcogsci/data/df_persianE1.rda’ ‘bcogsci/data/df_polarity.rda’
       ‘bcogsci/data/df_powerpose.rda’ ‘bcogsci/data/df_red.rda’
       ‘bcogsci/data/df_smithE1.rda’ ‘bcogsci/data/df_smithE2.rda’
       ‘bcogsci/data/df_swets08.rda’
─  building ‘bcogsci_0.0.0.9000.tar.gz’
   
* installing *source* package ‘bcogsci’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (bcogsci)
